### ISSUE TITLE
tokens are not like that

### ISSUE THREAD

**Issue by daleputo** [YABOI-py/Discord-string-Token-Generator#5]
token created are not like real tokens are!

they should be like

mfa.40YEfqnL7K-pPdMeTwWkAItyls-knXFSmdf0b4-b9Xd1fJ7gR7TOjN8JdeZtouWDH_7gK6C6Y4kA393Tjeqa

**Comment by MonkeMan32** [comment]
> token created are not like real tokens are!
> 
> they should be like
> 
> mfa.40YEfqnL7K-pPdMeTwWkAItyls-knXFSmdf0b4-b9Xd1fJ7gR7TOjN8JdeZtouWDH_7gK6C6Y4kA393Tjeqa

bro look at the fucking code 💀

**Comment by Pr0t0ns** [comment]
> Idiotic skid thkse are mfa tokens be aka tokens with 2FA they're both tokens just one has multi factor auth aka mfa

Lol both of u stupid, ur deadass generating a random string in the format of a discord token. Make a real generator using requests, httpx, or http.client cuz the chances of you getting a single valid working token out of this "Discord String Token Generator" are probably the same odds of winning the lottery XD. Also Discord updated their token format to start with MTA now.

**Comment by YABOI-py** [comment]
Check my other repos u slow ong

**Comment by Pr0t0ns** [comment]
> Check my other repos u slow ong

"Im slow", lmfao you can't even fix an indentation error you def a skid lol. I bet ur waiting for Xhulo or Vichy to release a new update so you can skid it lmfaooo xdd

**Comment by s0pt0n** [comment]
@YABOI-py  lol motherfucker faggot I could kick ur ass in python. I fixed the fucking error and everything and you can't? god damn I am a beginner motherfucker. Stop calling people slow lmfao 12 year old motherfucker.

**Comment by Pr0t0ns** [comment]
> @YABOI-py lol motherfucker faggot I could kick ur ass in python. I fixed the fucking error and everything and you can't? god damn I am a beginner motherfucker. Stop calling people slow lmfao 12 year old motherfucker.

Yo Chill out, it's not that deep💀

**Comment by s0pt0n** [comment]
nah bro this owner motherfucker shouldn't even be owner he knows we are right but he can't admit it so we force it out of him

**Comment by YABOI-py** [comment]
Bro responding on a 7 month old github 😯☝️

**Comment by YABOI-py** [comment]
@s0pt0n  admit what NIGA ur black ass money came outa nowhere looking for chicken

**Comment by s0pt0n** [comment]
> @s0pt0n admit what NIGA ur black ass money came outa nowhere looking for chicken

my man really tried to call me a black ass monkey, when im white.

**Comment by s0pt0n** [comment]
that shows your intelligence

**Comment by s0pt0n** [comment]
> Bro responding on a 7 month old github 😯☝️

bro still not being able to fix 7 month old errors and charging 350 for a gen you skidded motherfucker try me 😂

**Comment by YABOI-py** [comment]
who tf even gonna fix that shit and why u spending time on it 💀  + pooron + skid + black + ratio + gtf off my dick ;) <3

**Comment by YABOI-py** [comment]
joined 4 hours ago 😮 ☝️

**Comment by s0pt0n** [comment]
> joined 4 hours ago 😮 ☝️

look like I give a shit surprised you could find the join date

**Comment by s0pt0n** [comment]
> who tf even gonna fix that shit and why u spending time on it 💀 + pooron + skid + black + ratio + gtf off my dick ;) <3

someone who cares about their clients dumbass 💀what ratio you have no followers. lmfao mf

**Comment by YABOI-py** [comment]
their "clients" goes to a 7 month old github post 😂

**Comment by s0pt0n** [comment]
mf don't use that excuse. You updated this thing 4 months ago, + you still have to help your clients you dirty piece of shit.

**Comment by s0pt0n** [comment]
there are 1 year old github posts that work mf your code just sucks in general even your new shit

**Comment by s0pt0n** [comment]
so "get off my dick" with that shit.

**Comment by YABOI-py** [comment]
clients that go to a github page i didnt post this for ppl + u fr made an acc just to talk shit ong u a lil bitch get bitches first ong

**Comment by YABOI-py** [comment]
bro think github repos are a must and u gotta take them seriously cause theyre a job u getting paid for it ong brother

**Comment by YABOI-py** [comment]
i feel u that github live too hard man these mfs out here not helpin their clients

**Comment by s0pt0n** [comment]
> clients that go to a github page i didnt post this for ppl + u fr made an acc just to talk shit ong u a lil bitch get bitches first ong

mf I made this github account to post non skidded repos

**Comment by s0pt0n** [comment]
> bro think github repos are a must and u gotta take them seriously cause theyre a job u getting paid for it ong brother

you're selling a skidded client for $350 mf be quiet with that making money shit

**Comment by s0pt0n** [comment]
> i feel u that github life too hard man these mfs out here not helpin their clients

yeah you mf you're supposed to, that's how you get less members you dumbass.

**Comment by YABOI-py** [comment]
saying im selling my clients a skidded program for no reason idk who tf u are u aint shit nor ever seen me code u gotta be on sum shit bro give me that

**Comment by YABOI-py** [comment]
https://tenor.com/view/anonymous-kid-dancing-big-brain-cock-tiktok-gif-20094477

**Comment by YABOI-py** [comment]
this niga going off on a github post 😭

**Comment by s0pt0n** [comment]
> saying im selling my clients a skidded program for no reason idk who tf u are u aint shit nor ever seen me code u gotta be on sum shit bro give me that

your source code is public mf i've seen it its ass

**Comment by YABOI-py** [comment]
ur autism be kickin in or u aint gettin no boner fr

**Comment by s0pt0n** [comment]
> this niga going off on a github post 😭

nah im going off on a mf idiot

**Comment by YABOI-py** [comment]
not it isnt public LMFAO

**Comment by s0pt0n** [comment]
mf this was your code from 4 months ago

**Comment by s0pt0n** [comment]
and i've seen your shit from today too, none of it is good.

**Comment by s0pt0n** [comment]
you're a beginner a skid you know it deep inside

**Comment by YABOI-py** [comment]
code share !

**Comment by YABOI-py** [comment]
and idk what gen u talkin ab ong ur crazy

**Comment by s0pt0n** [comment]
> and idk what gen u talkin ab ong ur crazy

bro check all of your source code your a skid mf.

**Comment by s0pt0n** [comment]
and who tf makes their python files encrypted.

**Comment by YABOI-py** [comment]
bro which i litaraly have a gen that i made and im still busy on that shit hasnt been sent to anyone 💀

**Comment by YABOI-py** [comment]
code share nigar YABOI#7377

**Comment by YABOI-py** [comment]
BRO FOLDED LMFAO CANT CODE AND NEEDS HELP

**Comment by xhuloo** [comment]
> > Check my other repos u slow ong
> 
> "Im slow", lmfao you can't even fix an indentation error you def a skid lol. I bet ur waiting for Xhulo or Vichy to release a new update so you can skid it lmfaooo xdd

LMFAOOAOA

**Comment by xhuloo** [comment]
> BRO FOLDED LMFAO CANT CODE AND NEEDS HELP

u cant code for shit either 😹😹😹

**Comment by YABOI-py** [comment]
Closed fr folded ![IMG_3801.gif](https://user-images.githubusercontent.com/89107550/180920662-3f4737bc-4361-4c56-8b02-88fcbbe77634.gif)
